### ISSUE TITLE
Improve device name consistency

### ISSUE THREAD

**Issue by rudolfs** [getsenic/dev-board#1]
Device naming should be consistent in the app.
- [x] NUIMO should be always all-caps
- [x] "Sonos" should be used for any Sonos device
- [x] "Philips Hue" for Philips Hue devices
- [x] show MAC/IP addresses in DEV mode

For more details:
https://docs.google.com/document/d/1Jghi4sLu5uZ-3tVBq5Z8-dB0PvIQTXRpSBcMLUUmqcU
https://projects.invisionapp.com/d/main#/console/13219317/276338141/preview

**Comment by TheMeaningfulEngineer** [comment]
Is this a meta repo where we discuss process issues?

**Comment by rudolfs** [comment]
If a task spans multiple repos we make an issue here and #ref all the PRs to the respective issue.

**Comment by TheMeaningfulEngineer** [comment]
Could you shortly reference during the sync?
First time I'm seeing it used and would like a way for task that span multiple repos.
