### ISSUE TITLE
Image flashing transparency  

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [getsenic/dev-board#5]
@kelada 
Pull request spanning across multiple repos. 

https://github.com/getsenic/senic-os/pull/116
https://github.com/getsenic/senic-infrastructure/pull/28

I've been experiencing issues of not knowing what image has been burned and having to 
boot to check this. This adds some transparency to the process.

It will add the distro version in the image name without influencing the symlink:

```
# ls senic-os-*                                                                   
senic-os-dev-senic-hub-0.1.9-20180212123854.rootfs.ext4
senic-os-dev-senic-hub-0.1.9-20180212123854.rootfs.manifest
senic-os-dev-senic-hub-0.1.9-20180212123854.rootfs.mender
senic-os-dev-senic-hub-0.1.9-20180212123854.sdimg
senic-os-dev-senic-hub-0.1.9-20180212123854.testdata.json
senic-os-dev-senic-hub.ext4
senic-os-dev-senic-hub.manifest
senic-os-dev-senic-hub.mender
senic-os-dev-senic-hub.sdimg
senic-os-dev-senic-hub.testdata.json
```

The flashing of the image starts with the print of the image being flashed:

```
$ make write-os-ubuntu sddev=sdb image=senic-os-dev

Flashing image:  senic-os-dev-senic-hub-0.1.9-20180212123854.sdimg 
```

Tested on Ubuntu. Please check if the Mac version is working and merge.

**Comment by TheMeaningfulEngineer** [comment]
@baali 
Don't know when Jonathan is back today and it's been two days for the PR.
You have time to try it out?

**Comment by baali** [comment]
@TheMeaningfulEngineer Trying it out, will follow up with comments/results.

**Comment by baali** [comment]
Tested it out, on Ubuntu system, works :+1:

**Comment by TheMeaningfulEngineer** [comment]
@rudolfs You have some time to test this on a mac?

**Comment by rudolfs** [comment]
Works for me.
